#!/usr/bin/env bash
# This script behaves like a clock

HOURS=0
while [ $HOURS -le 12 ];
do 
    echo Hour: $HOURS
	MINUTES=1
        while [ $MINUTES -le 59 ]
            do
                echo $MINUTES
		MINUTES=$(( MINUTES + 1 ))
	     done
    HOURS=$(( HOURS + 1 ))        
done
